# -*- coding: utf-8 -*-
"""data.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Lbthl8zqGQjh2OTuxK_QIjZPz_vntki7
"""

import pandas as pd
import numpy as np

from google.colab import files
uploaded = files.upload()
import io
df = pd.read_csv(io.BytesIO(uploaded['ASC3TWzf9.csv']))

df.replace( to_replace=-9999.90,
    value=np.nan,
    inplace=True,
    limit=None,
    regex=False,
    method='pad',)
df.replace( to_replace=-9999.9004,
    value=np.nan,
    inplace=True,
    limit=None,
    regex=False,
    method='pad',)
df.replace( to_replace=-10000.0,
    value=np.nan,
    inplace=True,
    limit=None,
    regex=False,
    method='pad',)
final = df.drop(0).astype(float).interpolate()
final.tail(60)

.to_csv('data.csv', index=False)
files.download('data.csv')

final['DateTime'] = 1009843200 + final.day*86400 + final.hr*3600
final.tail()

final['DateTime'] = pd.to_datetime(final["DateTime"], unit='s')
final.tail(60)

final1 = final.resample('3H', on='DateTime').mean()

final1.head(60)

final1.shape

final1.tail()

final1.to_csv('Featuredata.csv', index=False)
files.download('Featuredata.csv')