# -*- coding: utf-8 -*-
"""KP.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1AxCRNAdz5T-x9gjMOcHzNRJAuyRx_8D-
"""

import pandas as pd

from google.colab import files
uploaded = files.upload()

import io
df = pd.read_csv(io.BytesIO(uploaded['kp0206.csv']))

single = df.set_index('Column1', append=True).stack().reset_index().drop('level_2',1).drop('level_0',1)

single.columns = ['Date','KP']

single['KP'] = single['KP'].map(lambda x: x.lstrip('+-').rstrip('o'))
single['KP'] = single['KP'].str.replace(r'\D', '')

single.head(5)

from google.colab import files
uploaded = files.upload()
import io
df1 = pd.read_csv(io.BytesIO(uploaded['kp0207.csv']))
single1 = df1.set_index('Column1', append=True).stack().reset_index().drop('level_2',1).drop('level_0',1)
single1.columns = ['Date','KP']
single1['KP'] = single1['KP'].map(lambda x: x.lstrip('+-').rstrip('o'))
single1['KP'] = single1['KP'].str.replace(r'\D', '')
single1.head()

from google.colab import files
uploaded = files.upload()
import io
df2 = pd.read_csv(io.BytesIO(uploaded['kp0208.csv']))
single2 = df2.set_index('Column1', append=True).stack().reset_index().drop('level_2',1).drop('level_0',1)
single2.columns = ['Date','KP']
single2['KP'] = single2['KP'].map(lambda x: x.lstrip('+-').rstrip('o'))
single2['KP'] = single2['KP'].str.replace(r'\D', '')
single2.head()

from google.colab import files
uploaded = files.upload()
import io
df3 = pd.read_csv(io.BytesIO(uploaded['kp0209.csv']))
single3 = df3.set_index('Column1', append=True).stack().reset_index().drop('level_2',1).drop('level_0',1)
single3.columns = ['Date','KP']
single3['KP'] = single3['KP'].map(lambda x: x.lstrip('+-').rstrip('o'))
single3['KP'] = single3['KP'].str.replace(r'\D', '')
single3.head()

from google.colab import files
uploaded = files.upload()
import io
df4 = pd.read_csv(io.BytesIO(uploaded['kp0210.csv']))
single4 = df4.set_index('Column1', append=True).stack().reset_index().drop('level_2',1).drop('level_0',1)
single4.columns = ['Date','KP']
single4['KP'] = single4['KP'].map(lambda x: x.lstrip('+-').rstrip('o'))
single4['KP'] = single4['KP'].str.replace(r'\D', '')
single4.head()

from google.colab import files
uploaded = files.upload()
import io
df5 = pd.read_csv(io.BytesIO(uploaded['kp0211.csv']))
single5 = df5.set_index('Column1', append=True).stack().reset_index().drop('level_2',1).drop('level_0',1)
single5.columns = ['Date','KP']
single5['KP'] = single5['KP'].map(lambda x: x.lstrip('+-').rstrip('o'))
single5['KP'] = single5['KP'].str.replace(r'\D', '')
single5.head()

from google.colab import files
uploaded = files.upload()
import io
df6 = pd.read_csv(io.BytesIO(uploaded['kp0212.csv']))
single6 = df6.set_index('Column1', append=True).stack().reset_index().drop('level_2',1).drop('level_0',1)
single6.columns = ['Date','KP']
single6['KP'] = single6['KP'].map(lambda x: x.lstrip('+-').rstrip('o'))
single6['KP'] = single6['KP'].str.replace(r'\D', '')
single6.head()

KP_main =  pd.concat([single, single1, single2, single3, single4, single5, single6], ignore_index=True)
KP_main.tail(80)

KP_main.to_csv('KPdata.csv', index=False)
files.download('KPdata.csv')