# -*- coding: utf-8 -*-
"""KP_NN_Model.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_FdA3Y4Um9pQ1OivPMl8yEwjUkF2o-2c
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from google.colab import files
uploaded = files.upload()
import io
Features = pd.read_csv(io.BytesIO(uploaded['Featuredata.csv']))

from google.colab import files
uploaded = files.upload()
import io
KP = pd.read_csv(io.BytesIO(uploaded['KPdata.csv']))

Features.head(20)

df = pd.concat([Features, KP], axis=1)
df.head(30)

df = df.drop(['year','day','hr','min','sec','Date'],axis=1)

df = df[df['Np'].notna()]

df

from sklearn.model_selection import train_test_split

X = df[['Np','Tp','Alpha_ratio','Vp','V_rtn_r','V_rtn_t','V_rtn_n','V_gse_x','V_gse_y','V_gse_z','V_gsm_x','V_gsm_y','V_gsm_z','B_rtn_r','B_rtn_t','B_rtn_n','B_gse_x','B_gse_y','B_gse_z','B_gsm_x','B_gsm_y','B_gsm_z','Bmag','pos_gse_x','pos_gse_y','pos_gse_z','pos_gsm_x','pos_gsm_y','pos_gsm_z']].values

Y = df[['KP']].values

X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.3,random_state=42)

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()

scaler.fit(X_train)

X_train = scaler.transform(X_train)

X_test = scaler.transform(X_test)

from tensorflow.keras.models import Sequential

from tensorflow.keras.layers import Dense

model = Sequential()

model.add(Dense(29,activation='tanh'))
model.add(Dense(29,activation='relu'))
model.add(Dense(29,activation='tanh'))

model.add(Dense(1))
model.compile(optimizer='adam', loss='mse')

model.fit(x=X_train, y=Y_train, epochs=50)

model.evaluate(X_test,Y_test,verbose=0)

testP = model.predict(X_test)
testP = pd.Series(testP.reshape(488,))
testP = testP.round(0)

pred_df = pd.DataFrame(Y_test,columns=['True Y'])

pred_df = pd.concat([pred_df,testP],axis=1)
pred_df.columns = ['True KP', 'Estimated KP']
pred_df.head(60)

pred_df.loc[pred_df['True KP'] == pred_df['Estimated KP']].count()

pred_df.plot(figsize=(35,5))

